version: '2'
services:
    wildfly: 
        build: images/wildfly
        ports:
            - "8080:8080"
            - "9090:9990"
        links:
            - mysql:db
    mysql:
        build: images/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "6060:80"
        links:
            - mysql:db
